openapi: 3.0.0
info:
  title: API Documentation
  version: 1.0.0
paths:
  /gyms/{gymId}/time-entries:
    post:
      summary: Create Check-in
      parameters:
        - name: gymId
          in: path
          required: true
          schema:
            type: string
      responses:
        "201":
          description: Check-in created successfully.
  /time-entries/history:
    get:
      summary: Check-in History
      responses:
        "200":
          description: List of time-entries.
  /time-entries/metrics:
    get:
      summary: Check-in Metrics
      responses:
        "200":
          description: Metrics of time-entries.
  /time-entries/{TimeEntryId}/validate:
    patch:
      summary: Validate Check-in
      parameters:
        - name: TimeEntryId
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Check-in validated successfully.
  /gyms/search:
    get:
      summary: Search Gyms
      responses:
        "200":
          description: List of gyms matching the search criteria.
  /gyms/nearby:
    get:
      summary: Nearby Gyms
      responses:
        "200":
          description: List of nearby gyms.
  /gyms:
    post:
      summary: Create Gym
      responses:
        "201":
          description: Gym created successfully.
  /users:
    post:
      summary: Register User
      responses:
        "201":
          description: User registered successfully.
  /sessions:
    post:
      summary: Authenticate Session
      responses:
        "200":
          description: User authenticated successfully.
  /token/refresh:
    patch:
      summary: Refresh Token
      responses:
        "200":
          description: Token refreshed successfully.
  /me:
    get:
      summary: User Profile
      responses:
        "200":
          description: User profile retrieved successfully.
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - BearerAuth: []
